### ISSUE TITLE
Do you like implement inline-editor and optional WYSIWYG?

### ISSUE THREAD

**Issue by adw0rd** [bennylope/django-addendum#8]
Your application I almost fit!

As I see it in final form:
- There is a special templatetag, as the "snippet", but without specifying a token (optional)
- There is a model with fields: token, text, created_at / updated_at + languages ​​like you have now

Process:
1. In some templates inserted such blocks
   {% snippet%} Hello, Kitty! {% endsnippet%}
2. If we "user.is_staff", the toolbar appears on the page "Editable mode (Languages: en / ru / zh and Logout link)" for each snippet-block there is a link "Edit"
3. By clicking on the "Edit" appears inline-editor like that http://ckeditor.com/demo#inline
4. When saving "Hello, Kitty!", If we do not specify a token for the snippet, then we get the hash from the "text (original, from template) + template_name" as a token

Are you interested in such a change in your application?

**Comment by bennylope** [comment]
Thanks, this is quite thoughtful. There are two changes proposed here:

- Modal editing from the front-end (could be done independently of unnamed snippet tags)
- Snippet tags without snippet names (depends on front-end editing)

My thoughts on your points:

1. I am ambivalent about totally removing the snippet name (see below).
2. It might be better if it checked the user's permissions, rather than just staff status.
3. Okay. Note that the edit modal should be very simple, in how it works for the user and in terms of what front-end code is required to ship.
4. Clever! But how do you get the `template_name` into the tag? Aside from the fact that I don't think this is technically feasible - since the template name isn't accessible in the template context unless explicitly provided, and that's a step down from just giving a snippet name - I think this creates problems where you might want a snippet throughout several templates and now need to update each one individually. *I'd recommend basing this only on the wrapped text, with the understanding that if you wrap the same text in different places, each location will be updated as one.*

Now a few suggested constraints: it should be backwards compatible with the current form of naming snippets. Two reasons:

1. No need to break stuff (I'm using the old format, for one)
2. There may be cases where integrating the JS into a site is problematic on some sites, and it's desirable to be able to edit named snippets (and only named snippets) from the admin.

If you're willing to take these concerns into consideration and start a new branch, go for it!

**Comment by adw0rd** [comment]
> But how do you get the template_name into the tag?

key = generate_key(token.source[0].loadname, nodelist[0].s)

**Comment by adw0rd** [comment]
> If you're willing to take these concerns into consideration and start a new branch, go for it!

Okay, tomorrow I present my prototype :-)

**Comment by adw0rd** [comment]
[First implementation](https://github.com/adw0rd/django-addendum-inline/commit/1c3a3a03e56827de62a37c845709ea8a48266472). Now is working, but need to refactor
